name: 'Close stale issues'
on:
  schedule:
    - cron: '30 1 * * *'
    workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: 'This issue is stale because there has been no activity for 25 days. Please comment or remove the stale label, or else this will be closed in 5 days.'
          close-issue-message: 'This issue was closed because there has been no activity for 30 days.'
          days-before-stale: 25
          days-before-close: 5
          days-before-pr-close: -1
