#if !macro
package scripts;
import funkin.backend.scripting.HardcodedScript;
import funkin.backend.scripting.events.*;
import funkin.backend.scripting.events.character.*;
import funkin.backend.scripting.events.dialogue.*;
import funkin.backend.scripting.events.discord.*;
import funkin.backend.scripting.events.gameover.*;
import funkin.backend.scripting.events.gameplay.*;
import funkin.backend.scripting.events.healthicon.*;
import funkin.backend.scripting.events.menu.*;
import funkin.backend.scripting.events.note.*;
import funkin.backend.scripting.events.shader.*;
import funkin.backend.scripting.events.soundtray.*;
import funkin.backend.scripting.events.splash.*;
import funkin.backend.scripting.events.sprite.*;
import funkin.backend.scripting.events.stage.*;

import StringTools;
import haxe.Json;
import Xml;

import openfl.utils.Assets;
import lime.app.Application;
import funkin.backend.system.Main;

import flixel.FlxG;
import flixel.FlxSprite;
import flixel.FlxBasic;
import flixel.FlxCamera;
import flixel.tweens.FlxEase;
import flixel.tweens.FlxTween;
import flixel.sound.FlxSound;
import flixel.system.FlxAssets;
import flixel.math.FlxMath;
import flixel.group.FlxGroup;
import flixel.group.FlxGroup.FlxTypedGroup;
import flixel.group.FlxSpriteGroup;
import flixel.addons.text.FlxTypeText;
import flixel.text.FlxText;
import flixel.util.FlxTimer;
import flixel.math.FlxPoint;
import flixel.util.FlxAxes;
import flixel.util.FlxColor;
import funkin.backend.scripting.ModState;
import funkin.backend.scripting.ModSubState;
import funkin.game.PlayState;
import funkin.game.GameOverSubstate;
import funkin.game.HealthIcon;
import funkin.game.HudCamera;
import funkin.game.Note;
import funkin.game.Strum;
import funkin.game.StrumLine;
import funkin.game.Character;
import funkin.menus.PauseSubState;
import funkin.menus.FreeplayState;
import funkin.menus.MainMenuState;
import funkin.menus.PauseSubState;
import funkin.menus.StoryMenuState;
import funkin.menus.TitleState;
import funkin.options.Options;
import funkin.backend.assets.Paths;
import funkin.backend.system.Conductor;
import funkin.backend.shaders.FunkinShader;
import funkin.backend.shaders.CustomShader;
import funkin.backend.FunkinText;
import animate.FlxAnimate;
import funkin.backend.FunkinSprite;
import funkin.menus.ui.Alphabet;
import funkin.backend.system.Flags;

import funkin.backend.utils.CoolUtil;
import funkin.backend.utils.IniUtil;
import funkin.backend.utils.XMLUtil;
#if sys 
import funkin.backend.utils.ZipUtil; 
#end
import funkin.backend.utils.MarkdownUtil;
import funkin.backend.utils.EngineUtil;
import funkin.backend.utils.ThreadUtil;
import funkin.backend.utils.MemoryUtil;
import funkin.backend.utils.BitmapUtil;
import funkin.backend.utils.TranslationUtil;
#end